apiVersion: apps/v1
kind: Deployment
metadata:
  name: site
  labels:
    app: site
spec:
  replicas: 1
  selector:
    matchLabels:
      app: site
  template:
    metadata:
      labels:
        app: site
    spec:
      containers:
      - name: site
        image: nginx:alpine
        #args:
        #- /bin/sh
        #- touch newfile.sh
        #- echo "This container runs" >> newfile.sh
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-service
spec:
  selector:
    app: site
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8005
      nodePort: 30002
